### PR TITLE
NYT News Article Clone

### PR DESCRIPTION
**Pull request by ahzia**
The is my first microverse project which is a clone of a new york times NEWS article.
First I have set up linters and then prepared the assets needed for the project.
After that, I worked on HTML and CSS for different parts of the article, and I used CSS flex Box and CSS grid for Positioning.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Invalid Code Review Request :x: 

__Hi @ahzia :wave: I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reason(s):__

- [ ] Some of your linter checks were not successful: to consider this project ready for review, you need to ensure that all GitHub Action Checks are running successfully. Kindly fix the linter errors.


This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!


* * *
**Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * * 

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

**Comment by ahzia** [comment]
@teekaytech  Thanks for your review,
I solved all linters error except for 1 error:
27:9  ✖  Unexpected unit   length-zero-no-unit
I checked my style.css line 27 but it doesn't look that it have any problem,
Can you help me on how I can solve this issue.
Thanks

**Comment by teekaytech** [comment]
> @teekaytech Thanks for your review,
> I solved all linters error except for 1 error:
> 27:9 heavy_multiplication_x Unexpected unit length-zero-no-unit
> I checked my style.css line 27 but it doesn't look that it have any problem,
> Can you help me on how I can solve this issue.
> Thanks


Hello, @ahzia I think I can help :blush: 

On line 27 of your ~/style/style.css (top: 0px;), the linter is telling you to remove the unit (px). When the value of your CSS rule is zero(0), adding the unit (i.e. px) is not necessary. I think this clear solve the error.

**Comment by ahzia** [comment]
Thanks, @teekaytech  for Your Help. :)

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @ahzia     ! :wave: :wave:

#### You have done well so far, I had to take a second look cause your project looks almost exactly like the actual site!  :clap: However, there are changes required for you to make in order for this project to be approved. _**Note that you have 2 more reviews before you reach the code review limit.**_ Kindly work on them and submit them for another code review.
- - -

### **Recommended**

**Section Specific requirements**
 - [x] Some parts of the main content texts have fonts that are larger than what is on the page. I'll recommend using [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help with this.
- [x] The left section of the navbar needs a little more spacing between them. "Space and Cosmos" should be written in block letters.

- [x] **You are missing certain parts of your project which includes:**
- The Paragraph with a small "thank you" note above it, as well as the Editors' Picks sidebar.

**Original**

Screenshot (123).
- [x] The Theory of Inflation section has its image bleeding into the texts. Please fix this.
- [x] The following sections need to be revisited and fixed. The images are bleeding into themselves, please add adequate spacings.
-  The Suggested Letters section,
- The Most Popular section,
- The Editor's Picks (at the base of the page just underneath the above-mentioned section), and
- The footer (It is missing the necessary icons).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by ahzia** [comment]
@Temmarie  Thank you for your review;
I couldn't understand some of your feedbacks that is about "image bleeding", I have double-checked my code and project and couldn't find any problem.
I think the problem is with your browser screen size because it looks ok in my browser, Please take a look at the project screenshot
app_screenshot

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @ahzia  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Review by descholar-ceo — APPROVED** [review]

**Pull request merged**
